### ISSUE TITLE
i18n support: "Missing helper: '__'

### ISSUE THREAD

**Issue by dmitriy-01** [sails101/using-handlebars#1]
I'm getting this error when trying to use {{__ 'some string'}} on the view:

```
{"message":"Missing helper: '__'","name":"Error"}
```

Should this __ helper be registered first?

**Comment by dmitriy-01** [comment]
Actually error is happening only within each loop:

```
{{#each errors}}
    <div>{{__ this}}</div>
{{/each}}
```

**Comment by iberflow** [comment]
Anyone worked this out?

**Comment by sabrinaluo** [comment]
I met the same issue, do you have any solutions?

**Comment by dmitriy-01** [comment]
This trick worked for me:

Create a new Handlebars helper in config/views.js:

```
"__l": function (str, locale) {
      return sails.__({
        phrase: str,
        locale: locale
      });
}
```

And use it like this on handlebars view inside {{#each}} loop:

```
{{#each ...}}
   {{__l "String" ../req.locale}}
{{/each}}
```

**Comment by rich186** [comment]
It seems the `__` "helper" is not actually a handlebars helper. It is simply a function passed to the view via `res.locals`. That means it's subject to the same scope rules as a standard template var (whereas _real_ hbs helpers can be used in any context).

You therefore have 2 solutions: either use the solution posted by @websquared, or reference the helper as you would a template var. So for example, within a `{{#each}}` loop: `{{../__ "String"}}`.

**Comment by wuyanxin** [comment]
I can use {{i18n 'key'}} on the layout file, but can not use it on partials
